// ============================================================================
// UNDO.AI — SAGA COMPENSATION CONTRACTS & TOOL DEFINITIONS
// BUILDATHON 2026 AG02: The Agent With An Undo Button
// "GLM proposes WHAT to do. UNDO.AI controls HOW it is safely executed."
// ============================================================================

export interface CompensationContract {
  toolName: string;
  displayName: string;
  action: string;
  compensationAction: string | null;
  reversible: boolean;
  idempotent: boolean;
  requiresApproval: boolean;
  category: 'booking' | 'payment' | 'inventory' | 'shipment' | 'support' | 'notification' | 'system';
  description: string;
  compensationDescription: string | null;
  sideEffectDescription: string;
  rollbackStrategy: 'COMPENSATE' | 'CANCEL' | 'NONE' | 'HUMAN_ESCALATION';
}

export const COMPENSATION_REGISTRY: Record<string, CompensationContract> = {
  // ==========================================================================
  // 1. Cab / Ride Booking Domain (Urban Mobility)
  // ==========================================================================
  request_ride: {
    toolName: 'request_ride',
    displayName: 'Locate Nearest Fleet Driver',
    action: 'request_ride',
    compensationAction: null,
    reversible: false, // Read-only query: 0 side effects
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Queries driver GPS telemetry for nearest available vehicle in pickup zone.',
    compensationDescription: null,
    sideEffectDescription: 'Read-only fleet lookup (0 state mutations committed).',
    rollbackStrategy: 'NONE',
  },
  assign_driver: {
    toolName: 'assign_driver',
    displayName: 'Lock & Assign Driver',
    action: 'assign_driver',
    compensationAction: 'release_driver',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Locks driver and commits assignment to trip dispatch queue.',
    compensationDescription: 'Releases assigned driver back to active dispatch pool.',
    sideEffectDescription: 'Driver state: UNASSIGNED ➔ ALLOCATED.',
    rollbackStrategy: 'COMPENSATE',
  },
  reserve_cab: {
    toolName: 'reserve_cab',
    displayName: 'Reserve Cab Booking',
    action: 'reserve_cab',
    compensationAction: 'cancel_ride',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Places atomic reservation hold on cab vehicle in mobility dispatch engine.',
    compensationDescription: 'Cancels cab reservation and frees vehicle hold in mobility engine.',
    sideEffectDescription: 'Ride state: NOT_RESERVED ➔ CONFIRMED.',
    rollbackStrategy: 'COMPENSATE',
  },
  reserve_ride: {
    toolName: 'reserve_ride',
    displayName: 'Reserve Ride Record',
    action: 'reserve_ride',
    compensationAction: 'cancel_ride',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Commits trip record to database with status CONFIRMED.',
    compensationDescription: 'Updates trip record status from CONFIRMED to CANCELLED.',
    sideEffectDescription: 'Trip state: NOT_RESERVED ➔ CONFIRMED.',
    rollbackStrategy: 'COMPENSATE',
  },
  charge_fare: {
    toolName: 'charge_fare',
    displayName: 'Pre-Authorize Ride Fare',
    action: 'charge_fare',
    compensationAction: 'refund_payment',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'payment',
    description: 'Pre-authorizes trip fare on rider account ledger.',
    compensationDescription: 'Releases fare authorization and issues reverse credit refund.',
    sideEffectDescription: 'Payment ledger: NOT_CHARGED ➔ CHARGED.',
    rollbackStrategy: 'COMPENSATE',
  },
  charge_payment: {
    toolName: 'charge_payment',
    displayName: 'Capture Payment Transaction',
    action: 'charge_payment',
    compensationAction: 'refund_payment',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'payment',
    description: 'Captures transaction payment amount against customer card/account ledger.',
    compensationDescription: 'Executes gateway reverse refund transaction and credits account.',
    sideEffectDescription: 'Financial transaction: NOT_CHARGED ➔ CHARGED.',
    rollbackStrategy: 'COMPENSATE',
  },
  dispatch_otp: {
    toolName: 'dispatch_otp',
    displayName: 'Dispatch Ride OTP & Live ETA',
    action: 'dispatch_otp',
    compensationAction: null,
    reversible: false, // Irreversible external SMS/Push side effect
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Sends SMS/Push OTP to passenger.',
    compensationDescription: 'Cannot unsend delivered SMS transmission.',
    sideEffectDescription: 'External SMS notification: NOT_SENT ➔ SENT.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },

  // ==========================================================================
  // 2. Hotel Booking Domain (Hospitality & Travel)
  // ==========================================================================
  search_hotels: {
    toolName: 'search_hotels',
    displayName: 'Search Nearby Hotels',
    action: 'search_hotels',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Searches nearby Chennai hotel availability and real-time room inventories.',
    compensationDescription: null,
    sideEffectDescription: 'Read-only hotel catalog search (0 state mutations committed).',
    rollbackStrategy: 'NONE',
  },
  search_hotel: {
    toolName: 'search_hotel',
    displayName: 'Search Hotel Availability',
    action: 'search_hotel',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Queries central hotel reservation system for available room inventory.',
    compensationDescription: null,
    sideEffectDescription: 'Read-only inventory search (0 state mutations committed).',
    rollbackStrategy: 'NONE',
  },
  search_room: {
    toolName: 'search_room',
    displayName: 'Search Room Inventory',
    action: 'search_room',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Queries room inventory database for matching unit.',
    compensationDescription: null,
    sideEffectDescription: 'Read-only state query (No side effects created).',
    rollbackStrategy: 'NONE',
  },
  select_room: {
    toolName: 'select_room',
    displayName: 'Select Room Configuration',
    action: 'select_room',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Selects available room unit and computes tariff calculation.',
    compensationDescription: null,
    sideEffectDescription: 'Room status: AVAILABLE ➔ SELECTED (Read-only allocation).',
    rollbackStrategy: 'NONE',
  },
  reserve_room: {
    toolName: 'reserve_room',
    displayName: 'Reserve Room Hold',
    action: 'reserve_room',
    compensationAction: 'cancel_room_booking',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Places atomic hold on room in property management system.',
    compensationDescription: 'Releases room hold and marks room status back to AVAILABLE.',
    sideEffectDescription: 'Mutates room state: AVAILABLE ➔ RESERVED.',
    rollbackStrategy: 'COMPENSATE',
  },
  charge_card: {
    toolName: 'charge_card',
    displayName: 'Charge Customer Card',
    action: 'charge_card',
    compensationAction: 'refund_payment',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'payment',
    description: 'Captures payment against customer card with transaction ledger commit.',
    compensationDescription: 'Issues reverse credit transaction: REFUNDED back to customer.',
    sideEffectDescription: 'Financial side-effect: NOT_CHARGED ➔ CHARGED.',
    rollbackStrategy: 'COMPENSATE',
  },
  create_booking_ticket: {
    toolName: 'create_booking_ticket',
    displayName: 'Create Booking Ticket',
    action: 'create_booking_ticket',
    compensationAction: 'cancel_booking_ticket',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Issues authoritative guest booking voucher ticket in central hospitality ledger.',
    compensationDescription: 'Voids booking ticket and updates status to CANCELLED.',
    sideEffectDescription: 'Ticket state: NOT_CREATED ➔ CREATED (Active Voucher).',
    rollbackStrategy: 'COMPENSATE',
  },
  send_booking_confirmation: {
    toolName: 'send_booking_confirmation',
    displayName: 'Send Booking Confirmation Email',
    action: 'send_booking_confirmation',
    compensationAction: null,
    reversible: false, // Irreversible external email side effect!
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Dispatches verified hotel booking confirmation email.',
    compensationDescription: 'Cannot unsend delivered SMTP email.',
    sideEffectDescription: 'External immutable email: NOT_SENT ➔ SENT to guest inbox.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },
  send_confirmation: {
    toolName: 'send_confirmation',
    displayName: 'Send Confirmation Alert',
    action: 'send_confirmation',
    compensationAction: null,
    reversible: false, // Irreversible external side effect!
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Dispatches external SMTP/SMS notification.',
    compensationDescription: 'Cannot unsend delivered SMTP email or SMS message.',
    sideEffectDescription: 'External immutable communication: NOT_SENT ➔ SENT.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },

  // ==========================================================================
  // 3. E-Commerce Order Domain (Retail & Inventory)
  // ==========================================================================
  check_stock: {
    toolName: 'check_stock',
    displayName: 'Check Warehouse SKU Stock',
    action: 'check_stock',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'inventory',
    description: 'Queries warehouse ERP database for SKU stock level.',
    compensationDescription: null,
    sideEffectDescription: 'Read-only inventory inquiry (0 stock locks created).',
    rollbackStrategy: 'NONE',
  },
  create_order: {
    toolName: 'create_order',
    displayName: 'Create Order Record',
    action: 'create_order',
    compensationAction: 'cancel_order',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'system',
    description: 'Generates new customer order record in database with status PENDING.',
    compensationDescription: 'Marks order record status as CANCELLED and purges active cart locks.',
    sideEffectDescription: 'Database record: NOT_CREATED ➔ CREATED.',
    rollbackStrategy: 'COMPENSATE',
  },
  reserve_inventory: {
    toolName: 'reserve_inventory',
    displayName: 'Reserve Warehouse Inventory',
    action: 'reserve_inventory',
    compensationAction: 'release_inventory',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'inventory',
    description: 'Decrements warehouse SKU stock count and locks allocation.',
    compensationDescription: 'Increments warehouse SKU stock count back to restore inventory.',
    sideEffectDescription: 'Warehouse stock: AVAILABLE ➔ LOCKED.',
    rollbackStrategy: 'COMPENSATE',
  },
  process_order_payment: {
    toolName: 'process_order_payment',
    displayName: 'Process Order Payment',
    action: 'process_order_payment',
    compensationAction: 'refund_order_payment',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'payment',
    description: 'Charges payment gateway profile for order total.',
    compensationDescription: 'Executes reverse settlement gateway refund.',
    sideEffectDescription: 'Financial transaction: NOT_CHARGED ➔ CHARGED.',
    rollbackStrategy: 'COMPENSATE',
  },
  create_shipment: {
    toolName: 'create_shipment',
    displayName: 'Generate Logistics Shipping Label',
    action: 'create_shipment',
    compensationAction: 'cancel_shipment',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'shipment',
    description: 'Creates tracking manifest and registers dispatch with carrier API.',
    compensationDescription: 'Calls carrier API to void airway bill and cancel dispatch manifest.',
    sideEffectDescription: 'Carrier manifest: NOT_CREATED ➔ DISPATCH_QUEUED.',
    rollbackStrategy: 'COMPENSATE',
  },
  send_order_confirmation: {
    toolName: 'send_order_confirmation',
    displayName: 'Send Order Receipt & Tracking Email',
    action: 'send_order_confirmation',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Sends order confirmation receipt.',
    compensationDescription: 'Cannot unsend delivered order confirmation email.',
    sideEffectDescription: 'External email: NOT_SENT ➔ SENT.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },

  // ==========================================================================
  // 4. Parcel Delivery Domain (Chennai Express Logistics)
  // ==========================================================================
  create_delivery: {
    toolName: 'create_delivery',
    displayName: 'Create Parcel Delivery Manifest',
    action: 'create_delivery',
    compensationAction: 'cancel_delivery',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'shipment',
    description: 'Creates dispatch manifest in central logistics hub.',
    compensationDescription: 'Cancels dispatch manifest and marks package as RETURNED_TO_HUB.',
    sideEffectDescription: 'Logistics manifest: NOT_CREATED ➔ CREATED.',
    rollbackStrategy: 'COMPENSATE',
  },
  assign_courier: {
    toolName: 'assign_courier',
    displayName: 'Assign Courier Driver',
    action: 'assign_courier',
    compensationAction: 'release_driver',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Assigns local courier driver to parcel delivery route.',
    compensationDescription: 'Releases courier driver back to dispatch pool.',
    sideEffectDescription: 'Courier driver: UNASSIGNED ➔ ALLOCATED.',
    rollbackStrategy: 'COMPENSATE',
  },
  reserve_vehicle: {
    toolName: 'reserve_vehicle',
    displayName: 'Reserve Cargo Slot in Van',
    action: 'reserve_vehicle',
    compensationAction: 'release_vehicle',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'booking',
    description: 'Locks cargo space in delivery van.',
    compensationDescription: 'Frees cargo space in delivery van.',
    sideEffectDescription: 'Vehicle cargo space: AVAILABLE ➔ RESERVED.',
    rollbackStrategy: 'COMPENSATE',
  },
  dispatch_package: {
    toolName: 'dispatch_package',
    displayName: 'Dispatch Package Out-For-Delivery',
    action: 'dispatch_package',
    compensationAction: 'cancel_dispatch',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'shipment',
    description: 'Marks package status as OUT_FOR_DELIVERY.',
    compensationDescription: 'Recalls package back to hub holding bay.',
    sideEffectDescription: 'Package state: AT_HUB ➔ OUT_FOR_DELIVERY.',
    rollbackStrategy: 'COMPENSATE',
  },
  notify_customer: {
    toolName: 'notify_customer',
    displayName: 'Send Live GPS Tracker SMS',
    action: 'notify_customer',
    compensationAction: null,
    reversible: false, // Irreversible external SMS
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Sends SMS tracking alert to customer.',
    compensationDescription: 'Cannot unsend delivered SMS transmission.',
    sideEffectDescription: 'External SMS network: NOT_SENT ➔ SENT.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },

  // ==========================================================================
  // 5. Customer Support SLA Domain (CRM & Goodwill Credits)
  // ==========================================================================
  fetch_ticket: {
    toolName: 'fetch_ticket',
    displayName: 'Fetch Support Ticket Details',
    action: 'fetch_ticket',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Queries support CRM for existing customer ticket record.',
    compensationDescription: null,
    sideEffectDescription: 'Read-only CRM query (0 state mutations committed).',
    rollbackStrategy: 'NONE',
  },
  classify_intent: {
    toolName: 'classify_intent',
    displayName: 'Classify Incident Priority',
    action: 'classify_intent',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Evaluates SLA policy and categorizes issue urgency.',
    compensationDescription: null,
    sideEffectDescription: 'Pure compute classification (No side effects created).',
    rollbackStrategy: 'NONE',
  },
  create_ticket: {
    toolName: 'create_ticket',
    displayName: 'Create Support Ticket Record',
    action: 'create_ticket',
    compensationAction: 'delete_ticket',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Opens new high-priority SLA ticket in support CRM.',
    compensationDescription: 'Deletes ticket or marks as CLOSED_CANCELLED in CRM.',
    sideEffectDescription: 'CRM Ticket: NOT_CREATED ➔ OPEN.',
    rollbackStrategy: 'COMPENSATE',
  },
  assign_specialist: {
    toolName: 'assign_specialist',
    displayName: 'Assign Senior Specialist',
    action: 'assign_specialist',
    compensationAction: 'unassign_agent',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Allocates specialist agent to ticket routing queue.',
    compensationDescription: 'Removes specialist assignment and returns agent to unallocated pool.',
    sideEffectDescription: 'Agent allocation: UNASSIGNED ➔ ALLOCATED.',
    rollbackStrategy: 'COMPENSATE',
  },
  update_customer_record: {
    toolName: 'update_customer_record',
    displayName: 'Upgrade Customer SLA Tier',
    action: 'update_customer_record',
    compensationAction: 'restore_customer_record',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'support',
    description: 'Updates CRM customer record: upgrades tier from Standard to Enterprise VIP.',
    compensationDescription: 'Restores original customer tier back to Standard.',
    sideEffectDescription: 'CRM state: Standard Tier ➔ Enterprise VIP.',
    rollbackStrategy: 'COMPENSATE',
  },
  create_resolution: {
    toolName: 'create_resolution',
    displayName: 'Issue SLA Service Resolution Credit',
    action: 'create_resolution',
    compensationAction: 'revert_resolution',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'payment',
    description: 'Issues service compensation credit to customer account ledger.',
    compensationDescription: 'Reverts service credit allocation in ledger.',
    sideEffectDescription: 'Account balance: +Credit SLA Resolution.',
    rollbackStrategy: 'COMPENSATE',
  },
  issue_goodwill_credit: {
    toolName: 'issue_goodwill_credit',
    displayName: 'Issue Goodwill Credit',
    action: 'issue_goodwill_credit',
    compensationAction: 'revert_resolution',
    reversible: true,
    idempotent: true,
    requiresApproval: false,
    category: 'payment',
    description: 'Issues goodwill compensation credit to customer account.',
    compensationDescription: 'Reverts goodwill credit in account ledger.',
    sideEffectDescription: 'Account balance: +Goodwill Credit.',
    rollbackStrategy: 'COMPENSATE',
  },
  send_resolution_email: {
    toolName: 'send_resolution_email',
    displayName: 'Send Incident Resolution Email',
    action: 'send_resolution_email',
    compensationAction: null,
    reversible: false,
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Dispatches resolution email.',
    compensationDescription: 'Cannot unsend delivered SMTP email.',
    sideEffectDescription: 'External email: NOT_SENT ➔ SENT.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },
  send_customer_notification: {
    toolName: 'send_customer_notification',
    displayName: 'Send SMS & Push Alert',
    action: 'send_customer_notification',
    compensationAction: null,
    reversible: false, // Irreversible external SMS
    idempotent: true,
    requiresApproval: true,
    category: 'notification',
    description: 'IRREVERSIBLE • NO COMPENSATION • APPROVAL REQUIRED. Sends external SMS alert.',
    compensationDescription: 'External SMS transmission is irreversible.',
    sideEffectDescription: 'External SMS network: NOT_SENT ➔ SENT.',
    rollbackStrategy: 'HUMAN_ESCALATION',
  },
};
